### ISSUE TITLE
Can't seem to use flake input as workspaceRoot argument to loadWorkspace

### ISSUE THREAD

**Issue by dorkeline** [pyproject-nix/uv2nix#62]
From what i can tell a flake input (and it's .outPath attribute) are strings with contexts, which `isPath` does not consider paths, and unless i'm missing something this makes it not possible to use a flake input as `workspaceRoot` for loading a workspace because of the `isPath workspaceRoot` assert in `loadWorkspace`. 

In my usecase im dealing with a monorepo collecting a bunch of other, uv, repos that don't want the nix files upstream, so i assumed i can just add them as inputs and use that instead of `./.`. 

If i missed some nix trick for getting a fully fletched path out of a string with context i'm very sorry, but i did play around in the repl a bit and learned weird things e.g. that the `path` or `toPath` return strings if you feed them a string with context?

Here's an example of trying a few obvious things in the repl that all end in producing a string instead of a path (nixpkgs being the flake input here):

```nix
nix-repl> typeOf nixpkgs
"set"

nix-repl> typeOf nixpkgs.outPath
"string"

nix-repl> typeOf (toPath nixpkgs.outPath)
"string"

nix-repl> typeOf (toPath nixpkgs)         
"string"

nix-repl> typeOf (toPath "${nixpkgs}")
"string"

nix-repl> typeOf (path { path = nixpkgs; })
copying '/nix/store/hfz1qqd0z8amlgn8qwich1dvkmldik36-source' to the store"string"

nix-repl> typeOf (/. + nixpkgs.outPath) # recommended by the toPath docs
error:
       … while calling the 'typeOf' builtin
         at «string»:1:1:
            1| typeOf (/. + nixpkgs.outPath) # recommended by the toPath docs
             | ^

       error: a string that refers to a store path cannot be appended to a path
       at «string»:1:12:
            1| typeOf (/. + nixpkgs.outPath) # recommended by the toPath docs
             |            ^

nix-repl> 
```

**Comment by chabardt** [comment]
I was just about to post the same issue. I have been trying the same commands as you, without any success.

**Comment by adisbladis** [comment]
> If i missed some nix trick for getting a fully fletched path out of a string with context i'm very sorry,

Off-hand idk if there is something more ergonomic than
``` nix
(/. + (builtins.unsafeDiscardStringContext "${nixpkgs}"))
```
Note that I'm not suggesting that you use this, it's terrible ^_^

I've changed it so that `workspaceRoot` can take a contextful string:
``` nix
lib.workspace.loadWorkspace { workspaceRoot = "${nixpkgs}"; }
```

**Comment by dorkeline** [comment]
Thanks for the quick commit! I had tried to fix this with a patch locally but i ran into another issue down the line that the last dependency for the venv (the project itself) fails in the unpackPhase now with an error like 
```
       > Running phase: unpackPhase
       > unpacking source archive /nix/store/dhszzy3l9z69s3bgrxnhq79mazg8dndr-source/.
       > Cannot copy /nix/store/dhszzy3l9z69s3bgrxnhq79mazg8dndr-source/. to .: destination already exists!
       > Did you specify two "srcs" with the same "name"?
       > do not know how to unpack source archive /nix/store/dhszzy3l9z69s3bgrxnhq79mazg8dndr-source/.
```
and i couldn't figure out why it is happening, uv2nix+pyproject.nix's codebase are quite complex to understand. Sadly with your commit the issue still seems to happen. 

Overriding the unpackPhase of the specific root dependencies like
```nix
my-root-project = prev.my-root-project.overrideAttrs (old: {
  unpackPhase = "cp -r $src .";
});
```
works around the issue for now it seems.

**Comment by adisbladis** [comment]
Added a test in f6946cdc037a43d4c7c6cd395bedea1fe11f33ff
