### ISSUE TITLE
Add more details to `README.md`

### ISSUE THREAD

**Issue by cospectrum** [pyproject-nix/uv2nix#74]
Quick usage example would be nice. Maybe Q&A section.
[poetry2nix](https://github.com/nix-community/poetry2nix) readme can be used for inspiration I think.

**Comment by adisbladis** [comment]
Having a very bare readme is a deliberate choice.

I don't believe that quickstart usage examples result in good outcomes for either users or maintainers.
It sets the wrong expectations for users, thinking that they can just copy & paste and have things work.
But things are more complicated than that, and you cannot actually wield the tooling successfully without more in-depth understanding of what's going on.

The `hello-world` example (with all of it's comments) is already the most minimal example that I want to expose anywhere.
