### ISSUE TITLE
Feature request: support for subpackages with dynamic dependencies

### ISSUE THREAD

**Issue by jfly** [pyproject-nix/uv2nix#77]
## The issue

I'm using uv2nix in a project with dynamic dependencies. This seems to work with `uv`, but not `uv2nix`. I've put together a simple repro over on https://github.com/jfly/2024-12-04-uv2nix-dynamic-dependencies-demo. This demo is `uv` workspace that contains a subpackage (`dynamic-deps`) which has a dynamic dependency on `tqdm`.

`uv` handles this well, note how `tqdm` ends up in the lockfile:

```shell
$ nix develop .#impure --command uv lock
Resolved 4 packages in 1ms
$ grep -B1 -A 5 '^name = "dynamic-deps"' uv.lock
[[package]]
name = "dynamic-deps"
version = "0.1.0"
source = { directory = "dynamic-deps" }
dependencies = [
    { name = "tqdm" },
]
```

However, `uv2nix` misses the dependency on `tqdm`:

```shell
$ nix develop .#uv2nix --command python -c 'import dynamic_deps'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/jeremy/tmp/uv2nix-dynamic-dependencies-demo/dynamic-deps/src/dynamic_deps/__init__.py", line 1, in <module>
    import tqdm
ModuleNotFoundError: No module named 'tqdm'
```

## Root cause

I've stepped through uv2nix, and I now understand where the bug is coming from, but I'm not sure how best to fix it:

1. [`workspaceProjects` is built by calling `loadUVPyproject`](https://github.com/pyproject-nix/uv2nix/blob/af99685eafd615ca714f3d31c53621b1417e9103/lib/workspace.nix/#L105-L111) on the subproject. This is a pure nix operation: it just reads [the pyproject.toml](https://github.com/jfly/2024-12-04-uv2nix-dynamic-dependencies-demo/blob/3590e1dc6f7d7a977bf98f193a4f4653cf9d5eac/dynamic-deps/pyproject.toml), which doesn't have any dependencies listed there (because they're dynamic).
2. Further down, [`resolved`](https://github.com/pyproject-nix/uv2nix/blob/af99685eafd615ca714f3d31c53621b1417e9103/lib/workspace.nix/#L151-L161) has the "correct" dependencies, because it's ultimately pulling them from `uv.lock`.
3. However, for workspace projects, we end up [using `workspaceProjects.${name}`](https://github.com/pyproject-nix/uv2nix/blob/af99685eafd615ca714f3d31c53621b1417e9103/lib/workspace.nix/#L178), which does not have the dynamic dependencies.

## How to fix it?

It seems to me that we'd rework [this logic](https://github.com/pyproject-nix/uv2nix/blob/af99685eafd615ca714f3d31c53621b1417e9103/lib/workspace.nix/#L178) to pull the dependencies from the lockfile rather than the pyproject.toml. I'm not exactly sure how to write this, though, as the dependencies from the lockfile are in a different attrset format than the dependencies parsed from pyproject.toml.

Happy to work on a PR if you can point me in the right direction here!

**Comment by adisbladis** [comment]
Thanks for a high quality issue report!

> It seems to me that we'd rework [this logic](https://github.com/pyproject-nix/uv2nix/blob/af99685eafd615ca714f3d31c53621b1417e9103/lib/workspace.nix/#L178) to pull the dependencies from the lockfile rather than the pyproject.toml. I'm not exactly sure how to write this, though, as the dependencies from the lockfile are in a different attrset format than the dependencies parsed from pyproject.toml.

Exactly. That format in the lock is already used for building non-local packages, so it already has a conversion function.
I used your example project as a test fixture for the fix in https://github.com/pyproject-nix/uv2nix/pull/78.
